name: Unit Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        kotlin-version: [1.8.21, 1.9.22]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :plugin:test --stacktrace -Pkotlin.version=${{ matrix.kotlin-version }}
